/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsCompareRow {
  relativePath: string
  action: string
  sourceSize?: number
  destSize?: number
  sourceMtime?: number
  destMtime?: number
}
export interface JsCompareResult {
  rows: Array<JsCompareRow>
  scanned: number
  toCopy: number
  unchanged: number
}
export interface JsSyncStats {
  scanned: number
  copied: number
  skipped: number
  errors: number
  bytesCopied: number
}
export interface JsCleanupStats {
  candidates: number
  deletedOrQuarantined: number
  skipped: number
  dryRunWouldAct: number
}
export declare function compare(source: string, destination: string): JsCompareResult
export declare function sync(source: string, destination: string): JsSyncStats
export declare function cleanup(source: string, destination: string, forceEnabled: boolean, dryRun: boolean): JsCleanupStats
export declare function purgeQuarantineDry(source: string, destination: string): JsCleanupStats
export declare function appDataPath(): string
